### PR TITLE
feat(Provider): create provider query and resolver

### LINKED ISSUE #14: create provider query
- create a `query` that takes a parameter of `id`  and a `resolver` for that query that returns a single `Provider` with an `id` that matches the `id` argument.

### PR DESCRIPTION
**Pull request by mareklubomirski**
closes #14

### CODE REVIEW

**Review by austenm — APPROVED** [review]

**Review by RhyecaRiley — COMMENTED** [review]
@matthewjwhitney what is the reason for using the GUID? Will we have that many providers that we will need a unique id? Or is it being used for security purposes?

edit: What I mean by unique id is that "big" of a unique id rather than using 1,2,3,4......

**Comment by MetaMatt1** [comment]
> @matthewjwhitney what is the reason for using the GUID? Will we have that many providers that we will need a unique id? Or is it being used for security purposes?
> 
> edit: What I mean by unique id is that "big" of a unique id rather than using 1,2,3,4......

@RhyecaRiley , great question, one of which doesn't have a black and white answer. there are advantages and disadvantages to using UUIDs vs Auto-Incrementing Integers and they could be argued all day but it is commonly best practice to use a UUID as a primary key in a database. You're right that we probably won't have many providers and collisions in ids is unlikely but the advantages of a uuid outweigh the advantages of an int from my perspective. If you have a compelling enough argument to use Integers in our database schema i'm all ears.

**Comment by RhyecaRiley** [comment]
I do not have an argument against it. Just wanted to get clarity on the topic and further understanding is all. The only time I ever saw UUIDs was for our tickets ids to prevent them from ever matching. Thank you for the explanation!

**Comment by MetaMatt1** [comment]
> I do not have an argument against it. Just wanted to get clarity on the topic and further understanding is all. The only time I ever saw UUIDs was for our tickets ids to prevent them from ever matching. Thank you for the explanation!

Most of the work has been in financial technology where we're dealing with billions of transactions and hundreds of thousands if not millions of people, so i guess i'm just used to uuids everywhere. integers are more performant though and for our project there's a compelling argument to use integers. you're making me rethink it to be honest. it's an excellent question you raise. i'd like to hear from Tim Riley if he ever decides to grace us with his presence haha. @metamang might be able to weigh in here as well with his experience in database analysis and management. He comes from finance too though so he's used to seeing uuids everywhere i'm sure as well. I think uuids are beautiful. i love how they're generated which is a fun topic to research if you're interested.

**Comment by RhyecaRiley** [comment]
I love them as well. Especially when I was taking Security classes at ASU. It is extremely interesting to see the difference between a UUID and a simple password. I think you can make an argument for both however in this situation. We will wait to see what the SQL masters have to say lol!

**Comment by triley72** [comment]
> > I do not have an argument against it. Just wanted to get clarity on the topic and further understanding is all. The only time I ever saw UUIDs was for our tickets ids to prevent them from ever matching. Thank you for the explanation!
> 
> Most of the work i've done has been in financial technology where we're dealing with billions of transactions and hundreds of thousands if not millions of people, so i guess i'm just used to uuids everywhere. integers are more performant though and for our project there's a compelling argument to use integers. you're making me rethink it to be honest. it's an excellent question you raise. i'd like to hear from Tim Riley if he ever decides to grace us with his presence haha. @metamang might be able to weigh in here as well with his experience in database analysis and management. He comes from finance too though so he's used to seeing uuids everywhere i'm sure as well. I think uuids are beautiful. i love how they're generated which is a fun topic to research if you're interested.

GUIDs are appropriate this day and age, just depends where you want generate them.  Check out this article as well, it mentions how Twitter leverages 64bit integers and discusses the GUID shift.  https://medium.com/ingeniouslysimple/why-did-we-shift-away-from-database-generated-ids-7e0e54a49bb3  We will still need to have proper INDEXING and PK/FK structure in place, in order to optimize data requests and utilization.

As this article mentions, the great thing about GUID's generated by server code versus DB INCREMENTATION is that you are no longer dependent upon the Database technology you are using to handle the task (i.e. the incrementor process).  We actually had an issue with this when we moved from ORACLE to MS SQL, because they handle this "process" differently.  Because most DB's (even MongoDB) have the GUID generation, it can be done on the DB or Server code, and we would still have the same benefits (portable data across various database technologies).  So whatever the decision is, I am down with it, we just might want to look at the 64bit integer approach that Twitter took.

Also, back in the day, we did not have the luxury of TB of data.  Sometimes we had servers that only had 2GB of total storage for the DB, so you had to be EXTREMELY efficient in how you Architected the DB.  Now a days, it doesn't really matter "too" much...storage is dirt cheap and Databases can grow to ridiculous size.

**Comment by MetaMatt1** [comment]
This discussion is awesome but isn't directly related to @mareklubomirski 's PR so i'm going to approve his PR and we can continue this discussion in google chat. thanks for the great discussion though!

**Review by MetaMatt1 — APPROVED** [review]

**Pull request merged**
